
import React, { useState } from 'react';
import type { DraftForCreation } from '../../App';

interface Message {
  id: number;
  sender: 'user' | 'ai';
  text: string;
  draftData?: DraftForCreation;
}

interface ChatMessageProps {
  message: Message;
  onStartDraft: (draft: DraftForCreation) => void;
}

// A simple markdown-like renderer
const renderText = (text: string) => {
    return text.split('\n').map((line, index) => {
        if (line.startsWith('* ')) {
            return <li key={index} className="ml-5 list-disc">{line.substring(2)}</li>;
        }
        return <p key={index}>{line || '\u00A0'}</p>; // Use non-breaking space for empty lines
    });
};

const ChatMessage: React.FC<ChatMessageProps> = ({ message, onStartDraft }) => {
    const isUser = message.sender === 'user';
    const [isDownloading, setIsDownloading] = useState(false);
    
    const wrapperClasses = isUser ? "flex justify-end" : "flex justify-start";
    const bubbleClasses = isUser 
        ? "bg-brand-secondary text-white" 
        : "bg-slate-100 text-slate-800";

    const getBase64Logo = async (): Promise<string | null> => {
        try {
            const response = await fetch('./maasim-logo.png');
            if (!response.ok) return null;
            const blob = await response.blob();
            return new Promise((resolve) => {
                const reader = new FileReader();
                reader.onloadend = () => resolve(reader.result as string);
                reader.readAsDataURL(blob);
            });
        } catch (error) {
            console.error("Failed to load logo for export:", error);
            return null;
        }
    };

    const handleDownload = async () => {
        if (isDownloading) return;
        setIsDownloading(true);

        try {
            const title = message.draftData ? `AI Draft - ${message.draftData.type}` : 'AI Assistant Response';
            const content = message.text;
            const logoData = await getBase64Logo();
            
            const formattedContent = content.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\n/g, '<br />');

            const htmlContent = `
                <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
                <head><meta charset='utf-8'><title>${title}</title></head>
                <body style="font-family: Arial, sans-serif; font-size: 11pt;">
                    <div style="text-align:center; margin-bottom: 20px;">
                        <table style="margin: 0 auto; border:none;">
                            <tr style="border:none;">
                                <td style="padding-right: 10px; border:none; vertical-align: middle;">
                                    ${logoData ? `<img src="${logoData}" width="75" height="75" />` : ''}
                                </td>
                                <td style="text-align: center; border:none; vertical-align: middle;">
                                    <p style="font-size: 13pt; margin: 0; font-weight: bold;">OFFICE OF THE SANGGUNIANG BAYAN</p>
                                    <p style="font-size: 9pt; margin: 0;">Municipality of Maasim, Province of Sarangani</p>
                                </td>
                            </tr>
                        </table>
                        <p style="font-size: 12pt; margin-top: 15px; font-weight: bold; text-transform: uppercase;">${title}</p>
                    </div>
                    <div>${formattedContent}</div>
                    <br /><br />
                    <div style="margin-top: 20px; font-size: 8pt; text-align: right; color: #555;">Generated by Computerized Legislative Tracking System - AI Assistant</div>
                </body>
                </html>
            `;

            const blob = new Blob(['\ufeff', htmlContent], { type: 'application/msword' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            const safeTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
            link.download = `${safeTitle}_${Date.now()}.doc`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } catch (err) {
            console.error("Failed to download Word document:", err);
            alert("Could not download the document. Please try again.");
        } finally {
            setIsDownloading(false);
        }
    };


    return (
        <div className={wrapperClasses}>
            <div className={`p-4 rounded-lg max-w-2xl ${bubbleClasses}`}>
                {message.draftData ? (
                    <div className="space-y-3">
                        <p>I have drafted the following {message.draftData.type}. You can save it to the archive for further editing and approval.</p>
                        <pre className="bg-slate-800 text-white p-4 rounded-lg text-xs whitespace-pre-wrap font-mono">
                            <code>{JSON.stringify(message.draftData.data, null, 2)}</code>
                        </pre>
                        <button 
                            onClick={() => onStartDraft(message.draftData!)}
                            className="w-full bg-emerald-500 text-white font-bold px-4 py-2 rounded-lg hover:bg-emerald-600 transition-colors"
                        >
                            Save to Archive
                        </button>
                    </div>
                ) : (
                    <div className="prose prose-sm max-w-none text-current">
                       {renderText(message.text)}
                    </div>
                )}

                {!isUser && (
                    <div className="mt-4 pt-3 border-t border-slate-200">
                        <button
                            onClick={handleDownload}
                            disabled={isDownloading}
                            className={`text-xs font-bold flex items-center gap-2 transition-opacity text-slate-500 hover:text-slate-800 disabled:opacity-50`}
                            aria-label="Download as Word document"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M3 17a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm3.293-7.707a1 1 0 011.414 0L9 10.586V3a1 1 0 112 0v7.586l1.293-1.293a1 1 0 111.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clipRule="evenodd" />
                            </svg>
                            {isDownloading ? 'Downloading...' : 'Download as Word'}
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ChatMessage;
